# Generated by Django 3.2.5 on 2021-07-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_courier_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('complete_time', models.DateTimeField()),
                ('assign_time', models.DateTimeField()),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.courier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAssignTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start_hour', models.IntegerField()),
                ('time_start_min', models.IntegerField()),
                ('time_finish_hour', models.IntegerField()),
                ('time_finish_min', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='CourierAssignTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start_hour', models.IntegerField()),
                ('time_start_min', models.IntegerField()),
                ('time_finish_hour', models.IntegerField()),
                ('time_finish_min', models.IntegerField()),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.courier')),
            ],
        ),
    ]
