# Generated by Django 3.2.5 on 2021-07-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_courierassigntime_order_orderassigntime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_orders', models.IntegerField(default=0)),
                ('last_complete_time', models.DateTimeField()),
                ('general_complete_seconds', models.FloatField()),
                ('region', models.IntegerField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.courier')),
            ],
        ),
    ]
