# Generated by Django 3.2.5 on 2021-07-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_completedorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courierassigntime',
            old_name='courier_id',
            new_name='courier',
        ),
    ]
